services:
    render:
        build:
            context: .
        command: 
            - /bin/bash
            - -c
            - |
                node -e 'import("./test.js").then(m => m.render())'
                cat out/diagram.svg | weasyprint - out/output.pdf
        volumes:
            - ./test/out:/var/task/out

    params:
        build:
            context: .
        command: node -e 'import("./test.js").then(m => m.params())'
        volumes:
            - ./test/out:/var/task/out
